<?php
/**
 * [BEGIN_COT_EXT]
 * Code=lastcommentsa
 * Name=Last Comments A
 * Description=Shows Latest comments in admin home
 * Version=1.0.1
 * Date=2023-04-19
 * Author=esclkm & Cotonti Team
 * Copyright=(c) esclkm & Cotonti Team 2011-2023
 * Auth_guests=R
 * Lock_guests=12345A
 * Auth_members=RW
 * Requires_plugins=comments
 * [END_COT_EXT]
 * 
 * [BEGIN_COT_EXT_CONFIG]
 * location=01:select:main,side:main:Panel
 * count=05:string::10:Count
 * truncate=10:string::200:Truncate
 * [END_COT_EXT_CONFIG]
 */

/**
 * plugin Admin home last comments for Cotonti Siena
 * 
 * @package lastcommentsa
 * @author esclkm & Cotonti Team
 * @copyright esclkm & Cotonti Team
 * @license BSD
 */

// Generated by Cotonti developer tool (littledev.ru)
defined('COT_CODE') or die('Wrong URL');

